### ISSUE TITLE
Getting error after Craft 4 upgrade

### ISSUE THREAD

**Issue by bhashkar007** [barrelstrength/sprout#326]
### Description

I upgraded a website from Craft 3 to Craft 4 including SproutSEO. It's throwing below error for some pages:
```
An Error occurred while handling another error:
yii\base\UnknownPropertyException: Setting unknown property: BarrelStrength\Sprout\meta\metadata\Metadata::enableMetaDetailsSearch in /var/www/html/vendor/yiisoft/yii2/base/Component.php:217
Stack trace:
#0 /var/www/html/vendor/yiisoft/yii2/BaseYii.php(557): yii\base\Component->__set('enableMetaDetai...', 1)
#1 /var/www/html/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure(Object(BarrelStrength\Sprout\meta\metadata\Metadata), Array)
#2 /var/www/html/vendor/craftcms/cms/src/base/Model.php(78): yii\base\BaseObject->__construct(Array)
#3 /var/www/html/vendor/barrelstrength/sprout/src/meta/metadata/Metadata.php(47): craft\base\Model->__construct(Array)
#4 /var/www/html/vendor/barrelstrength/sprout/src/meta/components/fields/ElementMetadataField.php(100): BarrelStrength\Sprout\meta\metadata\Metadata->__construct(Array, true)
#5 /var/www/html/vendor/craftcms/cms/src/base/Element.php(5344): BarrelStrength\Sprout\meta\components\fields\ElementMetadataField->normalizeValue('{"schemaTypeId"...', Object(craft\elements\Entry))
#6 /var/www/html/vendor/craftcms/cms/src/base/Element.php(4173): craft\base\Element->normalizeFieldValue('seoGeneral')
#7 /var/www/html/vendor/craftcms/cms/src/base/Element.php(4155): craft\base\Element->getFieldValue('seoGeneral')
#8 /var/www/html/vendor/craftcms/cms/src/base/Element.php(2185): craft\base\Element->clonedFieldValue('seoGeneral')
#9 /var/www/html/vendor/barrelstrength/sprout/src/meta/metadata/ElementMetadata.php(30): craft\base\Element->__get('seoGeneral')
#10 /var/www/html/vendor/barrelstrength/sprout/src/meta/metadata/OptimizeMetadata.php(166): BarrelStrength\Sprout\meta\metadata\ElementMetadata->getRawMetadataFromElement(Object(craft\elements\Entry))
#11 /var/www/html/vendor/barrelstrength/sprout/src/meta/metadata/OptimizeMetadata.php(148): BarrelStrength\Sprout\meta\metadata\OptimizeMetadata->getPrioritizedMetadataModel()
#12 /var/www/html/vendor/barrelstrength/sprout/src/meta/metadata/OptimizeMetadata.php(81): BarrelStrength\Sprout\meta\metadata\OptimizeMetadata->getMetadata(Object(craft\models\Site))
#13 /var/www/html/vendor/barrelstrength/sprout/src/meta/metadata/OptimizeMetadataHelper.php(32): BarrelStrength\Sprout\meta\metadata\OptimizeMetadata->registerMetadata(Object(craft\models\Site))
#14 [internal function]: BarrelStrength\Sprout\meta\metadata\OptimizeMetadataHelper::handleRenderMetadata(Object(yii\base\Event))
#15 /var/www/html/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Array, Object(yii\base\Event))
#16 /var/www/html/vendor/yiisoft/yii2/base/Component.php(650): yii\base\Event::trigger('craft\\web\\View', 'endPage', Object(yii\base\Event))
#17 /var/www/html/vendor/yiisoft/yii2/web/View.php(187): yii\base\Component->trigger('endPage')
#18 /var/www/html/vendor/craftcms/cms/src/web/View.php(1898): yii\web\View->endPage(false)
#19 /var/www/html/vendor/yiisoft/yii2/views/errorHandler/exception.php(544): craft\web\View->endPage()
#20 /var/www/html/vendor/yiisoft/yii2/base/View.php(348): require('/var/www/html/v...')
#21 /var/www/html/vendor/yiisoft/yii2/base/View.php(258): yii\base\View->renderPhpFile('/var/www/html/v...', Array)
#22 /var/www/html/vendor/yiisoft/yii2/web/ErrorHandler.php(270): yii\base\View->renderFile('/var/www/html/v...', Array, Object(craft\web\ErrorHandler))
#23 /var/www/html/vendor/yiisoft/yii2/web/ErrorHandler.php(126): yii\web\ErrorHandler->renderFile('@yii/views/erro...', Array)
#24 /var/www/html/vendor/craftcms/cms/src/web/ErrorHandler.php(192): yii\web\ErrorHandler->renderException(Object(yii\base\UnknownPropertyException))
#25 /var/www/html/vendor/yiisoft/yii2/base/ErrorHandler.php(152): craft\web\ErrorHandler->renderException(Object(yii\base\UnknownPropertyException))
#26 /var/www/html/vendor/craftcms/cms/src/web/ErrorHandler.php(66): yii\base\ErrorHandler->handleException(Object(yii\base\UnknownPropertyException))
#27 [internal function]: craft\web\ErrorHandler->handleException(Object(yii\base\UnknownPropertyException))
#28 {main}
```

### How to reproduce

Upgrade Craft 3 to Craft 4 with SproutSEO

### Sprout Version

4.45.0

### Craft Version

4.10.8

### Database Type Version

MySQL 8.0.33

**Comment by bhashkar007** [comment]
It seems like migrations didn't update entry content and still having setting data `enableMetaDetailsSearch`  in `SEO` column of `craft_content` table. 
```
{"schemaTypeId":null,"schemaOverrideTypeId":null,"enableMetaDetailsSearch":0,"enableMetaDetailsOpenGraph":0,"enableMetaDetailsTwitterCard":0,"enableMetaDetailsGeo":0,"enableMetaDetailsRobots":0,"title":"Subscription Services Agreement (April 06, 2022)","description":null,"keywords":null,"robots":null,"canonical":null,"region":null,"placename":null,"latitude":null,"longitude":null,"ogType":"website","ogUrl":null,"ogSiteName":null,"ogTitle":"Subscription Services Agreement (April 06, 2022)","ogDescription":null,"ogImage":null,"ogTransform":"","ogAuthor":null,"ogPublisher":null,"ogLocale":null,"twitterCard":"summary","twitterUrl":null,"twitterSite":null,"twitterTitle":"Subscription Services Agreement (April 06, 2022)","twitterDescription":null,"twitterImage":null,"twitterTransform":"","twitterCreator":null}
```
In my case, there are such 1400+ entries. I am not sure if it may happen with other setting variables. Please help.

Thank you,

**Comment by BenParizek** [comment]
This is resolved in Sprout SEO v4.45.1
