### ISSUE TITLE
SproutSEO Craft 3>4 upgrade migration issues

### ISSUE THREAD

**Issue by iamtompickering** [barrelstrength/sprout#340]
### Description

I've been trying to upgrade a site from Craft 3 > 4 and keep hitting migration errors as follows

```
Restore a database backup before trying again.
    > create table {{%sprout_redirects}} ... done (time: 0.002s)
    > create index craft_idx_clqmlxdllmepetnwoezrjvbumanlyxvouear on {{%sprout_redirects}} (oldUrl) ... done (time: 0.003s)
    > create index craft_idx_gkuetbuuoepbttqeviydladvrxffvrzhnybi on {{%sprout_redirects}} (newUrl) ... done (time: 0.003s)
    > create index craft_idx_mrqeoeruvffdekfouuodepodoqvmholudmgl on {{%sprout_redirects}} (statusCode) ... done (time: 0.002s)
    > create index craft_idx_nmbgoaiagksqoscoypszytvccpybwtlfqhmq on {{%sprout_redirects}} (count) ... done (time: 0.002s)
    > add foreign key craft_fk_pzocbrfyixntocmjcjnpcimynppezhbhujlv: {{%sprout_redirects}} (id) references {{%elements}} (id) ... done (time: 0.010s)
Exception: Undefined array key "cleanupProbability" (/Users/path/to/project-name/craft-3/vendor/barrelstrength/sprout/src/redirects/migrations/m211101_000001_migrate_settings_table_to_projectconfig.php:93)
#0 /Users/path/to/project-name/craft-3/vendor/barrelstrength/sprout/src/redirects/migrations/m211101_000001_migrate_settings_table_to_projectconfig.php(93): yii\base\ErrorHandler->handleError(2, 'Undefined array...', '/Users/tompicke...', 93)
#1 /Users/path/to/project-name/craft-3/vendor/barrelstrength/sprout/src/redirects/migrations/m211101_000001_migrate_settings_table_to_projectconfig.php(50): BarrelStrength\Sprout\redirects\migrations\m211101_000001_migrate_settings_table_to_projectconfig->prepareSettingsForMigration(Array, Array)
#2 /Users/path/to/project-name/craft-3/vendor/craftcms/cms/src/db/Migration.php(50): BarrelStrength\Sprout\redirects\migrations\m211101_000001_migrate_settings_table_to_projectconfig->safeUp()
#3 /Users/path/to/project-name/craft-3/vendor/craftcms/cms/src/db/MigrationManager.php(233): craft\db\Migration->up(true)
#4 /Users/path/to/project-name/craft-3/vendor/craftcms/cms/src/db/MigrationManager.php(149): craft\db\MigrationManager->migrateUp(Object(BarrelStrength\Sprout\redirects\migrations\m211101_000001_migrate_settings_table_to_projectconfig))
#5 /Users/path/to/project-name/craft-3/vendor/barrelstrength/sprout/src/core/db/SproutPluginMigrator.php(80): craft\db\MigrationManager->up()
#6 /Users/path/to/project-name/craft-3/vendor/barrelstrength/sprout/src/core/db/m000000_000000_sprout_plugin_migration.php(26): BarrelStrength\Sprout\core\db\SproutPluginMigrator->up()
#7 /Users/path/to/project-name/craft-3/vendor/craftcms/cms/src/db/Migration.php(50): BarrelStrength\Sprout\core\db\m000000_000000_sprout_plugin_migration->safeUp()
#8 /Users/path/to/project-name/craft-3/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(758): craft\db\Migration->up()
#9 /Users/path/to/project-name/craft-3/vendor/craftcms/cms/src/console/controllers/MigrateController.php(361): yii\console\controllers\BaseMigrateController->migrateUp('m240318_053732_...')
#10 [internal function]: craft\console\controllers\MigrateController->actionAll()
#11 /Users/path/to/project-name/craft-3/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#12 /Users/path/to/project-name/craft-3/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#13 /Users/path/to/project-name/craft-3/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction('all', Array)
#14 /Users/path/to/project-name/craft-3/vendor/craftcms/cms/src/console/ControllerTrait.php(90): yii\console\Controller->runAction('all', Array)
#15 /Users/path/to/project-name/craft-3/vendor/yiisoft/yii2/base/Module.php(552): craft\console\controllers\MigrateController->runAction('all', Array)
#16 /Users/path/to/project-name/craft-3/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#17 /Users/path/to/project-name/craft-3/vendor/craftcms/cms/src/console/Application.php(91): yii\console\Application->runAction('migrate/all', Array)
#18 /Users/path/to/project-name/craft-3/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('migrate/all', Array)
#19 /Users/path/to/project-name/craft-3/vendor/craftcms/cms/src/console/Application.php(122): yii\console\Application->handleRequest(Object(craft\console\Request))
#20 /Users/path/to/project-name/craft-3/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest(Object(craft\console\Request))
#21 /Users/path/to/project-name/craft-3/craft(22): yii\base\Application->run()
#22 {main}
Exception: An error occurred while executing the "BarrelStrength\Sprout\redirects\migrations\m211101_000001_migrate_settings_table_to_projectconfig migration: Undefined array key "cleanupProbability" (/Users/path/to/project-name/craft-3/vendor/craftcms/cms/src/db/MigrationManager.php:253)
#0 /Users/path/to/project-name/craft-3/vendor/craftcms/cms/src/db/MigrationManager.php(149): craft\db\MigrationManager->migrateUp(Object(BarrelStrength\Sprout\redirects\migrations\m211101_000001_migrate_settings_table_to_projectconfig))
#1 /Users/path/to/project-name/craft-3/vendor/barrelstrength/sprout/src/core/db/SproutPluginMigrator.php(80): craft\db\MigrationManager->up()
#2 /Users/path/to/project-name/craft-3/vendor/barrelstrength/sprout/src/core/db/m000000_000000_sprout_plugin_migration.php(26): BarrelStrength\Sprout\core\db\SproutPluginMigrator->up()
#3 /Users/path/to/project-name/craft-3/vendor/craftcms/cms/src/db/Migration.php(50): BarrelStrength\Sprout\core\db\m000000_000000_sprout_plugin_migration->safeUp()
#4 /Users/path/to/project-name/craft-3/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(758): craft\db\Migration->up()
#5 /Users/path/to/project-name/craft-3/vendor/craftcms/cms/src/console/controllers/MigrateController.php(361): yii\console\controllers\BaseMigrateController->migrateUp('m240318_053732_...')
#6 [internal function]: craft\console\controllers\MigrateController->actionAll()
#7 /Users/path/to/project-name/craft-3/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#8 /Users/path/to/project-name/craft-3/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#9 /Users/path/to/project-name/craft-3/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction('all', Array)
#10 /Users/path/to/project-name/craft-3/vendor/craftcms/cms/src/console/ControllerTrait.php(90): yii\console\Controller->runAction('all', Array)
#11 /Users/path/to/project-name/craft-3/vendor/yiisoft/yii2/base/Module.php(552): craft\console\controllers\MigrateController->runAction('all', Array)
#12 /Users/path/to/project-name/craft-3/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#13 /Users/path/to/project-name/craft-3/vendor/craftcms/cms/src/console/Application.php(91): yii\console\Application->runAction('migrate/all', Array)
#14 /Users/path/to/project-name/craft-3/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('migrate/all', Array)
#15 /Users/path/to/project-name/craft-3/vendor/craftcms/cms/src/console/Application.php(122): yii\console\Application->handleRequest(Object(craft\console\Request))
#16 /Users/path/to/project-name/craft-3/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest(Object(craft\console\Request))
#17 /Users/path/to/project-name/craft-3/craft(22): yii\base\Application->run()
#18 {main}
```Restore a database backup before trying again.
    > create table {{%sprout_redirects}} ... done (time: 0.002s)
    > create index craft_idx_clqmlxdllmepetnwoezrjvbumanlyxvouear on {{%sprout_redirects}} (oldUrl) ... done (time: 0.003s)
    > create index craft_idx_gkuetbuuoepbttqeviydladvrxffvrzhnybi on {{%sprout_redirects}} (newUrl) ... done (time: 0.003s)
    > create index craft_idx_mrqeoeruvffdekfouuodepodoqvmholudmgl on {{%sprout_redirects}} (statusCode) ... done (time: 0.002s)
    > create index craft_idx_nmbgoaiagksqoscoypszytvccpybwtlfqhmq on {{%sprout_redirects}} (count) ... done (time: 0.002s)
    > add foreign key craft_fk_pzocbrfyixntocmjcjnpcimynppezhbhujlv: {{%sprout_redirects}} (id) references {{%elements}} (id) ... done (time: 0.010s)
Exception: Undefined array key "cleanupProbability" (/Users/path/to/project-name/craft-3/vendor/barrelstrength/sprout/src/redirects/migrations/m211101_000001_migrate_settings_table_to_projectconfig.php:93)
#0 /Users/path/to/project-name/craft-3/vendor/barrelstrength/sprout/src/redirects/migrations/m211101_000001_migrate_settings_table_to_projectconfig.php(93): yii\base\ErrorHandler->handleError(2, 'Undefined array...', '/Users/tompicke...', 93)
#1 /Users/path/to/project-name/craft-3/vendor/barrelstrength/sprout/src/redirects/migrations/m211101_000001_migrate_settings_table_to_projectconfig.php(50): BarrelStrength\Sprout\redirects\migrations\m211101_000001_migrate_settings_table_to_projectconfig->prepareSettingsForMigration(Array, Array)
#2 /Users/path/to/project-name/craft-3/vendor/craftcms/cms/src/db/Migration.php(50): BarrelStrength\Sprout\redirects\migrations\m211101_000001_migrate_settings_table_to_projectconfig->safeUp()
#3 /Users/path/to/project-name/craft-3/vendor/craftcms/cms/src/db/MigrationManager.php(233): craft\db\Migration->up(true)
#4 /Users/path/to/project-name/craft-3/vendor/craftcms/cms/src/db/MigrationManager.php(149): craft\db\MigrationManager->migrateUp(Object(BarrelStrength\Sprout\redirects\migrations\m211101_000001_migrate_settings_table_to_projectconfig))
#5 /Users/path/to/project-name/craft-3/vendor/barrelstrength/sprout/src/core/db/SproutPluginMigrator.php(80): craft\db\MigrationManager->up()
#6 /Users/path/to/project-name/craft-3/vendor/barrelstrength/sprout/src/core/db/m000000_000000_sprout_plugin_migration.php(26): BarrelStrength\Sprout\core\db\SproutPluginMigrator->up()
#7 /Users/path/to/project-name/craft-3/vendor/craftcms/cms/src/db/Migration.php(50): BarrelStrength\Sprout\core\db\m000000_000000_sprout_plugin_migration->safeUp()
#8 /Users/path/to/project-name/craft-3/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(758): craft\db\Migration->up()
#9 /Users/path/to/project-name/craft-3/vendor/craftcms/cms/src/console/controllers/MigrateController.php(361): yii\console\controllers\BaseMigrateController->migrateUp('m240318_053732_...')
#10 [internal function]: craft\console\controllers\MigrateController->actionAll()
#11 /Users/path/to/project-name/craft-3/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#12 /Users/path/to/project-name/craft-3/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#13 /Users/path/to/project-name/craft-3/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction('all', Array)
#14 /Users/path/to/project-name/craft-3/vendor/craftcms/cms/src/console/ControllerTrait.php(90): yii\console\Controller->runAction('all', Array)
#15 /Users/path/to/project-name/craft-3/vendor/yiisoft/yii2/base/Module.php(552): craft\console\controllers\MigrateController->runAction('all', Array)
#16 /Users/path/to/project-name/craft-3/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#17 /Users/path/to/project-name/craft-3/vendor/craftcms/cms/src/console/Application.php(91): yii\console\Application->runAction('migrate/all', Array)
#18 /Users/path/to/project-name/craft-3/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('migrate/all', Array)
#19 /Users/path/to/project-name/craft-3/vendor/craftcms/cms/src/console/Application.php(122): yii\console\Application->handleRequest(Object(craft\console\Request))
#20 /Users/path/to/project-name/craft-3/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest(Object(craft\console\Request))
#21 /Users/path/to/project-name/craft-3/craft(22): yii\base\Application->run()
#22 {main}
Exception: An error occurred while executing the "BarrelStrength\Sprout\redirects\migrations\m211101_000001_migrate_settings_table_to_projectconfig migration: Undefined array key "cleanupProbability" (/Users/path/to/project-name/craft-3/vendor/craftcms/cms/src/db/MigrationManager.php:253)
#0 /Users/path/to/project-name/craft-3/vendor/craftcms/cms/src/db/MigrationManager.php(149): craft\db\MigrationManager->migrateUp(Object(BarrelStrength\Sprout\redirects\migrations\m211101_000001_migrate_settings_table_to_projectconfig))
#1 /Users/path/to/project-name/craft-3/vendor/barrelstrength/sprout/src/core/db/SproutPluginMigrator.php(80): craft\db\MigrationManager->up()
#2 /Users/path/to/project-name/craft-3/vendor/barrelstrength/sprout/src/core/db/m000000_000000_sprout_plugin_migration.php(26): BarrelStrength\Sprout\core\db\SproutPluginMigrator->up()
#3 /Users/path/to/project-name/craft-3/vendor/craftcms/cms/src/db/Migration.php(50): BarrelStrength\Sprout\core\db\m000000_000000_sprout_plugin_migration->safeUp()
#4 /Users/path/to/project-name/craft-3/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(758): craft\db\Migration->up()
#5 /Users/path/to/project-name/craft-3/vendor/craftcms/cms/src/console/controllers/MigrateController.php(361): yii\console\controllers\BaseMigrateController->migrateUp('m240318_053732_...')
#6 [internal function]: craft\console\controllers\MigrateController->actionAll()
#7 /Users/path/to/project-name/craft-3/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#8 /Users/path/to/project-name/craft-3/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#9 /Users/path/to/project-name/craft-3/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction('all', Array)
#10 /Users/path/to/project-name/craft-3/vendor/craftcms/cms/src/console/ControllerTrait.php(90): yii\console\Controller->runAction('all', Array)
#11 /Users/path/to/project-name/craft-3/vendor/yiisoft/yii2/base/Module.php(552): craft\console\controllers\MigrateController->runAction('all', Array)
#12 /Users/path/to/project-name/craft-3/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#13 /Users/path/to/project-name/craft-3/vendor/craftcms/cms/src/console/Application.php(91): yii\console\Application->runAction('migrate/all', Array)
#14 /Users/path/to/project-name/craft-3/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('migrate/all', Array)
#15 /Users/path/to/project-name/craft-3/vendor/craftcms/cms/src/console/Application.php(122): yii\console\Application->handleRequest(Object(craft\console\Request))
#16 /Users/path/to/project-name/craft-3/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest(Object(craft\console\Request))
#17 /Users/path/to/project-name/craft-3/craft(22): yii\base\Application->run()
#18 {main}

### How to reproduce

Upgrade from Craft 3 > 4, then run `./craft migrate/all`

### Sprout Version

4.45.0

### Craft Version

4.0.0

### Database Type Version

MYSQL

**Comment by iamtompickering** [comment]
@BenParizek could I get an update on this please?

**Comment by iamtompickering** [comment]
@BenParizek please can you get back to me on this???

**Comment by BenParizek** [comment]
@iamtompickering If you'd like to move forward before I get a fix out for this you can potentially do the following:

The error is saying that there is a missing setting in your Craft 3 database that the Craft 4 migration is assuming is there. You can find the setting in the `sprout_settings` table. If you find the row where `sprout_settings.model` = `barrelstrength\sproutbaseredirects\models\Settings` you can find the settings stored in JSON in the `sprout_settings.settings` column.

Update the JSON blob of those redirect settings in you Craft 3 database (before you run your upgrade migration) and add a setting for `"cleanupProbability":1000`. Assuming that's the only setting missing, you should then be able to re-run the upgrade migration.

**Comment by BenParizek** [comment]
This is resolved in Sprout SEO 4.45.1 and Redirects 4.47.3

**Comment by iamtompickering** [comment]
Hi @BenParizek just coming back to this - I ended up having to add `"cleanupProbability":1000, "trackRemoteIp": "",` to the settings table, as the `trackRemoteIp` value was also undefined.
